/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Estudiantes
 */
public class VentanaPrincipal extends javax.swing.JFrame{

    private final Modelo modelo;
    private Controlador control;
    private JTextField tablero [][] = new JTextField[9][9];
    private int [][] numeros = new int[9][9];
    String dificultad;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Modelo m) {
        super("Sudoku");
        modelo = m;
        for (int i=0;i<9;i++){
            for(int j=0;j<9;j++){
                tablero[i][j]= new JTextField();
                tablero[i][j].setBounds(20+(j*35), 70+(i*35), 30, 30);
                if(i>2 && i<6){
           if(j<3 || j>5){
               tablero[i][j].setBorder( new LineBorder(Color.CYAN) );
           }else{
           tablero[i][j].setBorder( new LineBorder(Color.BLACK) );
           }
        }else if(j>2 && j<6){
            tablero[i][j].setBorder( new LineBorder(Color.CYAN) );
        }else{
            tablero[i][j].setBorder( new LineBorder(Color.BLACK) );
        }
                this.add(tablero[i][j]);
                numeros[i][j]=0;
            }
        }
        initComponents();
        capturarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        terminar = new javax.swing.JButton();
        DificultadT = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        facil = new javax.swing.JButton();
        medio = new javax.swing.JButton();
        dificil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        terminar.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        terminar.setText("Terminar");

        DificultadT.setText("Dificultad:");

        facil.setText("Fácil");

        medio.setText("Medio");

        dificil.setText("Difícil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(DificultadT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dificil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DificultadT)
                            .addComponent(facil)
                            .addComponent(medio))
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dificil))
                .addGap(18, 18, 18)
                .addComponent(terminar, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DificultadT;
    private javax.swing.JButton dificil;
    private javax.swing.JButton facil;
    private javax.swing.JButton medio;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables
    private void capturarEventos() {
        facil.addActionListener(getControl());
        terminar.addActionListener(getControl());
        medio.addActionListener(getControl());
        dificil.addActionListener(getControl());
    }
    
    public Modelo getModelo() {
        return modelo;
    }
    
    public JButton getTerminar(){
        return terminar;
    }

    public int[][] getNumeros() {
        return numeros;
    }

    public JLabel getMensaje() {
        return mensaje;
    }

    public JTextField[][] getTablero() {
        return tablero;
    }

    public String getDificultad() {
        return dificultad;
    }

    public void setDificultad(String dificultad) {
        this.dificultad = dificultad;
    }

    public void setTablero(JTextField[][] tablero) {
        this.tablero = tablero;
    }

    public void setNumeros(int[][] numeros) {
        this.numeros = numeros;
    }

    public JButton getDificil() {
        return dificil;
    }

    public JButton getFacil() {
        return facil;
    }

    public JButton getMedio() {
        return medio;
    }
}

